### ISSUE TITLE
“transf_key”problem

### ISSUE THREAD

**Issue by Crispy-shark** [Coayala/metabodirect_tutorial#1]
What I want to know is that in the "Transformation networks" step, I have my own biochemical transformation table, how do I put it into the pipeline?

**Comment by Coayala** [comment]
To use your own biochemical transformation list, you need to create a CSV file similar to the default key provided by metabodirect (found here: https://github.com/Coayala/MetaboDirect/blob/main/metabodirect/data/transf_key.csv).
Here is a description of the columns in the csv file:
- **Group:** This column is only used to group the transformations for plotting. You can add your own groups, if you do not want to group your transformations, just make all of them belong to the same group (e.g., group A).
- **Transformation:** This column contains the name of your transformation
- **Formula:** This column contains the elements that are gained or loss during the transformation (e.g., the formula for methylation is CH3 as that is what is gained or loss).
- **mf:** This is the most important column as it indicates the mass difference associated with each transformation. This is used by metabodirect to assign transformations between the different *Masses/Peaks* that you have in your data.

Once you have you custom transformation file (`custom_transformations.csv`), it can be used in metabodirect using the option `-b`. For example:

```
metabodirect Report.csv metadata.csv -o tutorial_run -g Treatment -n median -t -b custom_transformations.csv
```

**Comment by Crispy-shark** [comment]
This solved my problem perfectly！ thanks
